# Generated by Django 6.0.4 on 2026-05-11 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="duration_minutes",
            field=models.PositiveIntegerField(
                blank=True, help_text="Spielzeit in Minuten", null=True
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="max_players",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="game",
            name="min_age",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="game",
            name="min_players",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
